/* tslint:disable */
/* eslint-disable */
/**
 * Lost Circulation Material
 * API for the LCM
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI {

    /**
     * Get all products
     */
    async getAllRaw(): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all products
     */
    async getAll(): Promise<Array<object>> {
        const response = await this.getAllRaw();
        return await response.value();
    }

}
