/* tslint:disable */
/* eslint-disable */
/**
 * Lost Circulation Material
 * API for the LCM
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductToJSON,
} from '../models';

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI {

    /**
     * Request to retrieve list of all products (id, name, supplier) and their related metadata. By default it will return all the metadata. Names of products may change and not be unique, so use the id as the identifier in the frontend. 
     * Get all products
     */
    async productsGetRaw(): Promise<runtime.ApiResponse<Array<Product>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * Request to retrieve list of all products (id, name, supplier) and their related metadata. By default it will return all the metadata. Names of products may change and not be unique, so use the id as the identifier in the frontend. 
     * Get all products
     */
    async productsGet(): Promise<Array<Product>> {
        const response = await this.productsGetRaw();
        return await response.value();
    }

}
