repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-ast
      language_version: python3.8
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3.8
      files: ^api/.*\.py$

- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: ^api/.*\.py$

- repo: https://github.com/prettier/prettier
  rev: 2.1.2
  hooks:
    - id: prettier
      files: ^web/.*\.(ts|tsx|js|css|html|json)$
      args: ['--config=web/.prettierrc.js', '--ignore-path=web/.prettierignore']

#- repo: local
#  hooks:
#    - id: yarntest
#      name: Yarn tests
#      entry: sh -c "cd web && CI=true npm run coverage"
#      language: system
#      files: ^web/.*\.(test.ts|test.tsx|test.js)$
#    - id: pytest
#      name: API Unit Tests with coverage
#      entry: sh -c "docker run --rm api-dev pytest tests"
#      language: system
