repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast
      language_version: python3.12
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml


- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.3'
  hooks:
    - id: ruff-format
      name: Code formatting
      files: ^api/.*\.py$

    - id: ruff
      name: Code linting
      files: ^api/.*\.py$
      args:
        - --fix
        - --unsafe-fixes


- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
    - id: prettier
      files: ^web/.*\.(ts|tsx|js|css|html|json)$
      args: ['--config=web/.prettierrc.js', '--ignore-path=web/.prettierignore']
