repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast
      language_version: python3.10
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml

- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
    - id: black
      language_version: python3.10
      files: ^api/.*\.py$

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests, --skip, B311]
      files: ^api/.*\.py$

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
    - id: prettier
      files: ^web/.*\.(ts|tsx|js|css|html|json)$
      args: ['--config=web/.prettierrc.js', '--ignore-path=web/.prettierignore']
