repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.4"
    hooks:
      - id: ruff-format
        name: Code formatting
        files: ^api/.*\.py$

      - id: ruff
        name: Code linting
        files: ^api/.*\.py$
        args:
          - --fix
          - --unsafe-fixes

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.4.4"
    hooks:
      - id: biome-check
        name: "Lint: biome (js/ts)"
        files: ^web/.*\.(ts|tsx|js|css|html|json)$
        additional_dependencies: ["@biomejs/biome@2.4.4"]
        args: ["--config-path", "."]
