services:
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:8080"
    depends_on:
      - web

  redis:
    image: dhi.io/redis:7.4.7-debian13-compat
    environment:
      REDIS_PASSWORD: 'very secret'
  oauth2-proxy:
    build: ./oauth2
    environment:
      REDIS_PASSWORD: 'very secret'
      OAUTH2_PROXY_COOKIE_SECRET: 'secure cookie'
      CLIENT_ID: "1dbc1e96-268d-41ad-894a-92a9fb85f954"
    secrets: 
      - client_secret
  api:
    build:
      context: ./api
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      FLASK_DEBUG: "true"
      TABLE_KEY: ${TABLE_KEY}
      APPINSIGHTS_CON_STRING: ${APPINSIGHTS_CON_STRING}
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/app/src

  web:
    build:
      context: ./web
      target: development
      args:
        APPINSIGHTS_CON_STRING: ${APPINSIGHTS_CON_STRING}
    restart: unless-stopped
    stdin_open: true
    environment:
      HMR_CLIENT_PORT: ${HMR_CLIENT_PORT:-}
      USE_POLLING: ${USE_POLLING:-false}
    volumes:
      - ./web/src:/code/src
secrets:
  client_secret:
    file: ./secrets/client_secret.txt
    