apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lcm
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: web
      src: ./web
      ports:
        - name: http
          port: 3000

    - name: api
      src: ./api
      environmentConfig:
        - environment: dev
          variables:
            ENVIRONMENT: production
      ports:
        - name: flask
          port: 5000
      publicPort: flask

    - name: proxy
      src: ./nginx/
      ports:
        - name: nginx
          port: 80
      publicPort: nginx
      
  dnsAppAlias:
    environment: dev
    component: proxy