apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lost-circulation-material
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: test
      build:
        from: test
  components:
    - name: web
      src: ./web
      ports:
        - name: http
          port: 3000

    - name: api
      src: ./api
      environmentConfig:
        - environment: prod
          variables:
            ENVIRONMENT: production
      ports:
        - name: flask
          port: 5000
      publicPort: flask
      secrets:
        - TABLE_KEY

    - name: proxy
      src: ./nginx/
      ports:
        - name: nginx
          port: 8080
      publicPort: nginx

  dnsAppAlias:
    environment: prod
    component: proxy
