apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lost-circulation-material
spec:
  build:
    useBuildKit: false
  environments:
    - name: prod
      build:
        from: prod
    - name: test
      build:
        from: master
  components:
    - name: redis
      src: ./redis
      secrets:
        - REDIS_PASSWORD
    - name: oauth2-proxy
      src: ./oauth2
      environment:
        OAUTH_CLIENT_ID: "1dbc1e96-268d-41ad-894a-92a9fb85f954"
      secrets:
        - OAUTH2_PROXY_COOKIE_SECRET
        - OAUTH2_PROXY_REDIS_PASSWORD
        - CLIENT_SECRET
    - name: web
      src: ./web
      ports:
        - name: http
          port: 3000
    - name: api
      src: ./api
      resources:
        requests:
          memory: "800Mi"
          cpu: "100m"
        limits:
          cpu: "4000m"
      environmentConfig:
        - environment: prod
          variables:
            ENVIRONMENT: production
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 8
            triggers:
            - name: cpu
              cpu:
                value: 85
            - name: memory
              memory:
                value: 75
        - environment: test
          variables:
            ENVIRONMENT: test
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 4
            triggers:
            - name: cpu
              cpu:
                value: 85
            - name: memory
              memory:
                value: 75
      ports:
        - name: flask
          port: 5000
      secrets:
        - TABLE_KEY
        - APPINSIGHTS_CON_STRING
        - SYNC_BLOBS_APP_URL
    - name: nginx
      src: ./nginx/
      ports:
        - name: nginx
          port: 8080
      publicPort: nginx

  dnsAppAlias:
    environment: prod
    component: nginx
