from enum import StrEnum


class BridgeOption(StrEnum):
    MAXIMUM_PORESIZE = "MAXIMUM_PORESIZE"
    AVERAGE_PORESIZE = "AVERAGE_PORESIZE"
    PERMEABILITY = "PERMEABILITY"
    CERAMIC_DISCS = "CERAMIC_DISCS"
