/* tslint:disable */
/* eslint-disable */
/**
 * Lost Circulation Material
 * API for the LCM
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    supplier?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    shortname?: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    cost?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    sackSize?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    co2?: number;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'supplier': !exists(json, 'supplier') ? undefined : json['supplier'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'shortname': !exists(json, 'shortname') ? undefined : json['shortname'],
        'cost': !exists(json, 'cost') ? undefined : json['cost'],
        'sackSize': !exists(json, 'sack_size') ? undefined : json['sack_size'],
        'co2': !exists(json, 'co2') ? undefined : json['co2'],
    };
}

export function ProjectToJSON(value?: Project | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'supplier': value.supplier,
        'description': value.description,
        'shortname': value.shortname,
        'cost': value.cost,
        'sack_size': value.sackSize,
        'co2': value.co2,
    };
}


