name: Algorithm-Report

on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Create report"
        run: docker compose build api && docker compose run -u 0 api python src/tests/optimizer_test.py

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: algorithm-report
          path: api/test_report.png
