name: "Push to master branch"
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build-test-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Create report"
        run: docker compose build api && docker compose run -u 0 api python src/tests/optimizer_test.py

      - name: Archive results
        uses: actions/upload-artifact@v7
        with:
          name: algorithm-report
          path: api/src/test_report.png
