name: CI

on: 
  workflow_dispatch:
  push:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build API test image"
        run: docker build --tag api-development ./api

      - name: "API UnitTests"
        run: docker run --rm -e TABEL_KEY="${{ secrets.TABEL_KEY }}" api-development pytest src/tests

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build web"
        run: docker build --tag web-development ./web

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --verbose
